remote_theme: mmistakes/minimal-mistakes
title: Liyang Xie
minimal-mistakes-skin: "mint"
layout: single
author_profile: true
author:
  name: "Liyang Xie"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "xieliyang@utexas.edu"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LY-Xie"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
